# Generated by Django 3.1.2 on 2021-01-02 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='listings',
            new_name='listing',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 6, 51, 20, 261970)),
        ),
    ]
