language: python

os:
  - linux

python:
  - "3.9"
  - "nightly"  # nightly build

matrix:
    allow_failures:
        - python: "nightly"

install:
  - pip install -r requirements.txt

jobs:
  include:
    - script: ./flake8
    name: "Linter"
